name: wave_blob
description: Wave Blob Animation
version: 1.0.0
repository: https://github.com/hosein-nadali/flutter-wave-blob/
homepage: https://github.com/hosein-nadali/flutter-wave-blob/

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'Example-1.gif'
    path: example-1.gif
  - description: 'Example-2.png'
    path: example-2.png
  - description: 'Example-3.png'
    path: example-3.png

flutter:
